platform :ios, '6.0'

pod 'AFNetworking'
pod 'MagicalRecord'
pod 'Facebook-iOS-SDK'                                                           
pod 'Firebase', '~> 1.0.0'

pod 'SDWebImage'                                                                 
pod 'ShareKit/Facebook'                                                          
pod 'JASidePanels'                                                               
pod 'MBProgressHUD'
pod 'JSMessagesViewController'
pod 'JSQSystemSoundPlayer'
pod 'JSONModel'
